# Generated by Django 5.1.6 on 2025-02-25 20:37

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('token', models.CharField(default=api.models.generate_provisioning_token, editable=False, max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('public_key', models.TextField()),
                ('plain_client_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_meter', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('transaction_type', models.CharField(choices=[('production', 'Production'), ('consumption', 'Consumption')], max_length=20)),
                ('energy_kwh', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smart_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.smartmeter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
