# Generated by Django 5.1.6 on 2025-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_provisioningtoken_token_smartmeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='plain_client_secret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
