# Generated by Django 5.1.6 on 2025-03-26 01:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clusterregistration_remove_smartmeter_device_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProvisioningToken',
        ),
        migrations.AlterField(
            model_name='clusterregistration',
            name='token',
            field=models.UUIDField(default=api.models.generate_provisioning_token, editable=False, unique=True),
        ),
    ]
