# Generated by Django 5.1.6 on 2025-03-26 01:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_provisioningtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterregistration',
            name='token',
            field=models.CharField(default=api.models.generate_provisioning_token, editable=False, max_length=32, unique=True),
        ),
    ]
