# Generated by Django 5.1.6 on 2025-02-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_smartmeter_plain_client_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('production', 'Production'), ('consumption', 'Consumption')], max_length=20)),
                ('energy_kwh', models.DecimalField(decimal_places=8, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smart_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.smartmeter')),
            ],
        ),
    ]
