# Generated by Django 5.1.6 on 2025-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clusterregistration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='raw_client_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
