# Generated by Django 5.1.6 on 2025-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_smartmeter_last_ping_ts_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='enode',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
