# Generated by Django 5.1.6 on 2025-04-28 00:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_smartmeter_enode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_id', models.CharField(max_length=1000)),
                ('state', models.CharField(choices=[('placed', 'Placed'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], default='placed', max_length=100)),
                ('total_amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('is_partial', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BCTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], null=True)),
                ('bc_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.bcorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
