# Generated by Django 5.1.6 on 2025-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bcorder_bctransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcorder',
            name='filled_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bcorder',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bcorder',
            name='order_id',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='bcorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bcorder',
            name='state',
            field=models.CharField(choices=[('placed', 'Placed'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], default='placed', max_length=10),
        ),
        migrations.AlterField(
            model_name='bcorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bctransaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bctransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bctransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
    ]
