# Generated by Django 5.1.6 on 2025-04-28 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bcorder_filled_amount_bcorder_order_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bctransaction',
            old_name='bc_order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='bctransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
