# Generated by Django 5.1.6 on 2025-05-01 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_bc_order_bctransaction_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcorder',
            name='smart_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.smartmeter'),
        ),
    ]
