# Generated by Django 5.1.6 on 2025-05-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bcorder_smart_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bctransaction',
            name='executed_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
