# Generated by Django 5.1.6 on 2025-05-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bctransaction_executed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcorder',
            name='smart_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smartmeter'),
        ),
    ]
