# Generated by Django 5.1.6 on 2025-05-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bcorder_smart_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcorder',
            name='smart_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.smartmeter'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
