version: "3.8"

services:
  der-cluster-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: der-cluster-1
    networks:
      - smart_grid
    ports:
      - "8001:8000"
    environment:
      - METER_ORIGIN=ws://der-cluster-1:8000
      - CENTRAL_SERVER_ORIGIN=http://host.docker.internal:8080

      # Lake: These creds won't work for everyone. It's just what I have in my local database.
      - CLIENT_ID=9d924af736604dd48769bfdaa94e67d6
      - CLIENT_SECRET=dBm0--cSQWxX3HYKIxStd4HoZaiFHmUguJlIEvFjXyo

  # der-cluster-2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: der-cluster-2
  #   networks:
  #     - smart_grid
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     - METER_ORIGIN=ws://der-cluster-2:8000

  # der-cluster-3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: der-cluster-3
  #   networks:
  #     - smart_grid
  #   ports:
  #     - "8003:8000"
  #   environment:
  #     - METER_ORIGIN=ws://der-cluster-3:8000

networks:
  smart_grid:
    driver: bridge
